### ISSUE TITLE
Automatically adding GitHub topics

### ISSUE THREAD

**Issue by jamen** [generate/generate-gh-repo#1]
GitHub just rolled "topics", which are pretty much like npm keywords but for GitHub.  One of my first thoughts was that now I have to manage them in two places!

It would be nice if this generator automatically pulled the ones from your `"keywords"` in `package.json`, and used those.

**Comment by jonschlinkert** [comment]
That would be great, but it looks like GitHub hasn't exposed this on the API yet, or at least it's not documented anywhere that I can find. We're looking into now, thanks for the issue. We'll let you know if we find anything

**Comment by jamen** [comment]
Hmm, now that I think about it tho, how would this work from `generate`'s perspective?  It sounds more like an `update` thing, because a new project might not have any keywords.

**Comment by jonschlinkert** [comment]
Hmm, true.I guess it depends on when you initialize a new github repo. I tend to already have most of the source files created and committed locally before I create the github repo. But still, it does seem like update would be more useful. We could do `updater-topics` once the API for it is exposed
